allowed_applications:
  - name: "worker"
    app_key: "37F129EF-687E-47AC-B0C4-CBF6516B37ED"
rules:
  - resource: $ipv4
    operator: equal
    target: 54.36.149.41
    action:
      name: alert_by_email
      parameters:
        - tech_lead@gmail.com
        - warning
  - resource: $status_code
    operator: equal
    target: 500
    action:
      name: alert_by_email
      parameters:
        - product_team@gmail.com
        - critical
